<?php

$xpdo_meta_map = array (
  'xPDOSimpleObject' => 
  array (
    0 => 'idSportsmen',
    1 => 'idSquad',
    2 => 'idSportsmenSquad',
    3 => 'idContact',
    4 => 'idChanges',
    5 => 'idPay',
    6 => 'idInvoice',
    7 => 'idInvoicePay',
    8 => 'idInvoiceType',
    9 => 'idSInvType',
    10 => 'idTrainer',
    11 => 'idClub',
    12 => 'idCity',
    13 => 'idLevel',
    14 => 'idSport',
    15 => 'idSchedule',
    16 => 'idLesson',
    17 => 'idFiles',
    18 => 'idShopItem',
    19 => 'idOrderItems',
    20 => 'idOrderPack',
    21 => 'idEvent',
    22 => 'idEventCategory',
    23 => 'idEventMember',
    24 => 'idLead',
    25 => 'idTascom',
    26 => 'idStatus',
    27 => 'idTmpl',
    28 => 'idMsg',
    29 => 'idExtid',
    30 => 'idConfig',
    31 => 'idTalk',
    32 => 'idRate',
    33 => 'idLink',
  ),
);